# Generated by Django 2.1 on 2019-02-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Causes',
            new_name='causes',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Diagnoses',
            new_name='diagnoses',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Symptoms',
            new_name='symptoms',
        ),
    ]
